services:
  - type: web
    name: arista-job-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: /jobs
