services:
  - type: web
    name: arista-job-api
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y wget curl gnupg unzip && \
      curl -sSL https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o chrome.deb && \
      apt install -y ./chrome.deb && \
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
